version: "3.3"
services:
  db:
    image: mongo
    environment:
      FLASK_ENV: development
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
  